services:
  python:
    build:
      context: .
      dockerfile: docker/python/Dockerfile
    volumes:
      - .:/app
    depends_on:
      - elasticsearch
    networks:
      - net

  elasticsearch:
    build:
      dockerfile: docker/elasticsearch/Dockerfile
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      # - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - xpack.security.enabled=false
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - elastic-data:/usr/share/elasticsearch/data
    networks:
      - net

  kibana:
    image: docker.elastic.co/kibana/kibana:8.9.0
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=${ELASTICSEARCH_SERVERS}
      - xpack.security.enabled=false
    volumes:
      - kibana-data:/usr/share/kibana/data
    depends_on:
      - elasticsearch
    networks:
      - net

networks:
  net:
    driver: bridge

volumes:
  elastic-data:
    driver: local
  kibana-data:
    driver: local
